/* -LICENSE-START-
 ** Copyright (c) 2012 Blackmagic Design
 **
 ** Permission is hereby granted, free of charge, to any person or organization
 ** obtaining a copy of the software and accompanying documentation covered by
 ** this license (the "Software") to use, reproduce, display, distribute,
 ** execute, and transmit the Software, and to prepare derivative works of the
 ** Software, and to permit third-parties to whom the Software is furnished to
 ** do so, all subject to the following:
 **
 ** The copyright notices in the Software and this entire statement, including
 ** the above license grant, this restriction and the following disclaimer,
 ** must be included in all copies of the Software, in whole or in part, and
 ** all derivative works of the Software, unless such copies or derivative
 ** works are solely in the form of machine-executable object code generated by
 ** a source language processor.
 **
 ** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 ** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 ** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 ** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 ** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 ** DEALINGS IN THE SOFTWARE.
 ** -LICENSE-END-
 */
//
// main.cpp
// LoopThroughWithOpenGLCompositing
//

/* Version 8 de DreamEverywhere - Juin 2016
 *
 * Camille Bataille
 * Léo Regnier-Lelong
 * Guillaume Renault
 *
 * Précédents:
 * Najib Riegert
 * Antonin Morel
 * Pierre-hamme Jerome
 *
 * Ajouts par rapport à la version précédente (2015)
 *      Amélioration des performances du logiciel. Moins de latence en sortie de carte BLACKMAGIC_DECKLINK
 *      Possibilité de patcher les E/S physique de la carte DeckLink aux E/S virtuelles de DreamEverywhere
 *      Suppression de la fonction Iris Virtuel sur le panneau principal
 *      Meilleure documentation du code source
 *
 * Dépendances :
 *  SDK Blackmagic 10.6.1
 *  OpenGL 3.1
 *  Qt4
 *
 * La classe LoopThroughWithOpenGLCompositing fournit une explication du fonctionnement du programme
 * Les méthodes et attributs des classes carte_bmd et openGLComposite sont entièrement commentées dans les fichiers .h
*/

#include <QApplication>
#include "LoopThroughWithOpenGLCompositing.h"

int main(int argc, char *argv[])
{
	QApplication app(argc, argv);

	LoopThroughWithOpenGLCompositing loopThrough;
	loopThrough.start();

	return app.exec();

}
